from banking import BankAccount, SavingsAccount, CheckingAccount, Customer, print_account_summary, DummyAccount

savings = SavingsAccount("Saloni", 1000, interest_rate=0.05)
checking = CheckingAccount("Aryan", 500, overdraft_limit=200)
savings.deposit(500)
checking.withdraw(600)  
savings.apply_interest()
merged = savings + checking
print("Merged Account:", merged)
customer = Customer("Milan")
customer.add_account(savings)
customer.add_account(checking)
customer.add_account(merged)
customer.transfer(savings, checking, 200)
print("Total Customer Balance:", customer.total_balance())
print("\nAccount Summaries:")
print_account_summary(savings)
print_account_summary(checking)
print_account_summary(merged)
dummy = DummyAccount("Pritam", 10000)
print_account_summary(dummy)
print("\nUsing str and repr:")
print(str(savings))
print(repr(savings))
print(str(checking))
print(repr(checking))
